
### !set auth eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3NzU1MTA1IiwiaWF0IjoxNjE5NDMyMjIwLCJzdWIiOiJ7XCJzZXNzaW9uSWRcIjpcIjc3NTUxMDVcIixcInVzZXJJZFwiOjc3NTUxMDUsXCJjb2RlXCI6XCIyMDIxMDIwMTAyOTA5NzEwNDAwXCIsXCJjZWxscGhvbmVcIjpcIjE2NioqKio5ODAwXCIsXCJpZGVudGl0eUF1dGhlbnRpY2F0aW9uU3RhdHVzXCI6MSxcInJlZ2lzdGVyQ2hhbm5lbFwiOlwiMDJcIixcInBvc3BhbFVzZXJJZFwiOjEyMDE4NjYxMTQ0Mzc2MzEzMSxcIm5hbWVcIjpcIi5LXCIsXCJhY2NvdW50VHlwZVwiOlwiQ1VTVE9NRVJfVVNFUlwiLFwiaGFzaENwXCI6XCIyYmtQQTc5NVZCdjNnMUpNXCJ9IiwiZXhwIjoxNjIyMDI0MjIwfQ.eeK7p3c1lSTSsaJ8SUOAa_kUAi_p_Eiv6o9Xo03h42s
### !header Host app.relxtech.com
### !header Origin https://app.relxtech.com
### !header Referer https://app.relxtech.com/mcrm/activity/64
### !header Accept-Language zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
### !header X-Requested-With com.tencent.mm
### !header XAccept application/json
### !header Content-Type application/json;charset=UTF-8
### !header User-Agent Mozilla/5.0${space}(Linux;${space}Android${space}10;${space}DT1901A${space}Build/QKQ1.191222.002;${space}wv)${space}AppleWebKit/537.36${space}(KHTML,${space}like${space}Gecko)${space}Version/4.0${space}Chrome/77.0.3865.120${space}MQQBrowser/6.2${space}TBS/045521${space}Mobile${space}Safari/537.36${space}MMWEBID/6454${space}MicroMessenger/8.0.1.1841(0x2800015D)${space}Process/tools${space}WeChat/arm64${space}Weixin${space}NetType/WIFI${space}Language/zh_CN${space}ABI/arm64
### !header Authorization Bearer${space}${auth}

#@relx优惠券1-1
POST https://app.relxtech.com/api/crm/coupon/draw
{
  "couponId": 520,
  "activityId": 73
}
### !set count 0
### print ${res.body.message}
### (set count (add ${count} 1))
### while ${count} < 3
### sleep 300


#@relx优惠券5-1
POST https://app.relxtech.com/api/crm/coupon/draw
{
  "couponId": 521,
  "activityId": 73
}

### print ${res.body.message}
### sleep 300

#@relx优惠券8-2
POST https://app.relxtech.com/api/crm/coupon/draw
{
  "couponId": 511,
  "activityId": 73
}

### print ${res.body.message}
### sleep 300

#//@relx优惠券100
//POST https://app.relxtech.com/api/crm/coupon/draw
//{
//  "couponId": 522,
//  "activityId": 73
//}

### //print ${res.body.message}